### PR TITLE
Initial refactoring of the Terraform code for SAT

### PR DESCRIPTION
**Pull request by alexott**
This includes following changes:

* Refactor the common code into a separate module (repo, job, data sources)
* Generate a dedicated PAT for use with SAT
* Code optimizations
* Update READMEs

TODOs:

* Test on all clouds
* Instead of individual READMEs for each cloud, consolidate everything in one, because most of the instructions are the same - it will be easier to support common changes

### CODE REVIEW

**Comment by alexott** [comment]
Cc: @airizarryDB @arunpamulapati

**Comment by alexott** [comment]
I'll try to retest all clluds tomorrow

**Comment by alexott** [comment]
Ok, changes were tested on all three clouds.

**Review by arunpamulapati — CHANGES_REQUESTED** [review]
Spoke to Alex , and requested the following changes which he kindly agreed.

1. We allow user to configure the existing DBSQL Warehouse (by giving the id) or we create one. This mitigates the issue of erroring if they have DBSQL  Warehouse with the name in the config.
GCP now asks where  gs_path_to_json = "gs://sat_dev/key/SA-1-key.json" is to avoid copying the private key to dbfs. 
           Appreciate if you can pull those back into your model.  (Or I can do those after our call on Monday )
2. We need to set the  PAT lifetime to 90 instead of 360 (To avoid: Cannot create token: Token lifetime must be less than or equal to the workspace max of 90 days,  as we recommend customers to set this value )

Alex is going to rebase and help with the minor updates.

**Comment by alexott** [comment]
@arunpamulapati I've rebased it to the latest `main` version

**Review by arunpamulapati — APPROVED** [review]
Tested and reviewed

**Pull request merged**
